### ISSUE TITLE
Automatic release builds get pushed to github's activity feed.

### ISSUE THREAD

**Issue by holly-hacker** [Francesco149/cubecalc-ui#1]
GitHub will put an entry in your github activity feed (including the rss feed) every time a release is created by a user you follow. It seems that the automatic releases in this repository count as a new release every time, causing them to show up multiple times in the activity feed.

This isn't a bug in this software and you are obviously allowed to set up your CI in any way you want, but I wanted to let you know in case you weren't aware :)

<details>
<summary>Example activity feed</summary>

![activity feed showing multiple entries for this repo](https://i.imgur.com/O1I8J4M.png)

</details>
<details>
<summary>Example RSS feed</summary>

![RSS feed showing multiple entries for this repo](https://i.imgur.com/65awpO6.png)

</details>

**Comment by Francesco149** [comment]
that kinda sucks, maybe if i set it as pre release it stops doing that?

**Comment by Francesco149** [comment]
I have changed it to be a prerelease. latest release was less than 1 min from this comment. see if that also shows up, hopefully not

**Comment by holly-hacker** [comment]
They show up in the same way, both in the RSS feed and in the activity feed:
<details>
<summary>Example</summary>

![activity feed](https://i.imgur.com/1cvPCKE.png)

![RSS feed](https://i.imgur.com/x0hXkRd.png)

</details>

**Comment by Francesco149** [comment]
seems to be a limitation of github's rss feed. it cannot differentiate between pre-releases and releases. all tools to auto release CI builds delete and recreate the release and the tag. I will just use the artifact links from github actions instead of making a nightly release then

**Comment by holly-hacker** [comment]
That certainly fixes it, thanks!
